services:
  - type: web
    name: taskify-ai
    env: node
    buildCommand: |
      npm install
      npm run clean
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - client/**
        - server/**
        - shared/**
        - vite.config.ts
        - tsconfig.json
        - tailwind.config.ts
        - postcss.config.js 